version: "3"

services:
  app:
    build:
      dockerfile: Dockerfile.master
      context: .
      args:
        VERSION: "development"
    volumes:
      - .:/go/src/myapp
      - ${HOME}/go:/go
    container_name: inception-go
    ports:
      - "8080:8080"
    env_file: ".env"